/**
	OpenGL information.
	Copyright (C) 2016  Valdemar Lindberg

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

*/
#include<stdio.h>
#include<stdlib.h>
#include<GL/gl.h>
#include<GL/glext.h>
#include<unistd.h>

/**
 *	Forward declared functions.
 */
extern void readargument(int argc, char** argv);
extern int giCreateMakeGLContext(void);
extern void giDeleteGLContext(void);

/*
 *	Converting character into a constant string in the precompiling stage.
 */
#define GLIF_STR_HELPER(x)  #x
#define GLIF_STR(x) GLIF_STR_HELPER(x)
#define GLIF_TMP_VARI(x) tmp##x

GLenum err;

GLint Integervtmp;
#define GLIF_CONSTANTI_PRINT(glenum)						\
		glGetIntegerv(glenum, &Integervtmp);		\
		printf(#glenum " : %d\n", Integervtmp);		\
		err = glGetError();							\

GLint64 Integervtmp64;
#define GLIF_CONSTANTI64_PRINT(glenum)					\
		glGetInteger64v(glenum, &Integervtmp64);	\
		printf(#glenum " : %ld\n", Integervtmp64);	\


GLfloat glGetFloatvtmp;
#define GLIF_CONSTANTF_PRINT(glenum)						\
		glGetFloatv(glenum, &glGetFloatvtmp);		\
		printf(#glenum " : %f\n", glGetFloatvtmp);	\


int main( int argc, char** argv){

	readargument(argc, argv);

	if(!giCreateMakeGLContext()){
		return EXIT_FAILURE;
	}

	/*	Display information.	*/
	printf("RENDERER %s\n", glGetString(GL_RENDERER));
	printf("VENDOR %s\n", glGetString(GL_VENDOR));
	printf("VERSION %s\n", glGetString(GL_VERSION));
	printf("SHADING_LANGUAGE_VERSION %s\n", glGetString(GL_SHADING_LANGUAGE_VERSION));
	printf("\n");

	/*	*/
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_UNIFORM_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_UNIFORM_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_ATOMIC_COUNTERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_WORK_GROUP_COUNT);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_WORK_GROUP_SIZE);
	GLIF_CONSTANTI_PRINT(GL_MAX_DEBUG_GROUP_STACK_DEPTH);

	/*	*/
	GLIF_CONSTANTI_PRINT(GL_NUM_COMPRESSED_TEXTURE_FORMATS);
	GLIF_CONSTANTI_PRINT(GL_COMPRESSED_TEXTURE_FORMATS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMPUTE_UNIFORM_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_3D_TEXTURE_SIZE);
	GLIF_CONSTANTI_PRINT(GL_MAX_ARRAY_TEXTURE_LAYERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_CLIP_DISTANCES);
	GLIF_CONSTANTI_PRINT(GL_MAX_COLOR_TEXTURE_SAMPLES);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMBINED_ATOMIC_COUNTERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS);
	GLIF_CONSTANTI_PRINT(GL_MAX_COMBINED_UNIFORM_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_CUBE_MAP_TEXTURE_SIZE);
	GLIF_CONSTANTI_PRINT(GL_MAX_DEPTH_TEXTURE_SAMPLES);
	GLIF_CONSTANTI_PRINT(GL_MAX_DRAW_BUFFERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_DUAL_SOURCE_DRAW_BUFFERS);
	GLIF_CONSTANTI64_PRINT(GL_MAX_ELEMENTS_INDICES);
	GLIF_CONSTANTI64_PRINT(GL_MAX_ELEMENTS_VERTICES);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAGMENT_ATOMIC_COUNTERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAGMENT_INPUT_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAGMENT_UNIFORM_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAGMENT_UNIFORM_VECTORS);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAGMENT_UNIFORM_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAMEBUFFER_WIDTH);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAMEBUFFER_HEIGHT);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAMEBUFFER_LAYERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_FRAMEBUFFER_SAMPLES);
	GLIF_CONSTANTI_PRINT(GL_MAX_GEOMETRY_ATOMIC_COUNTERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_GEOMETRY_INPUT_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_GEOMETRY_OUTPUT_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS);
	GLIF_CONSTANTI_PRINT(GL_MAX_GEOMETRY_UNIFORM_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_GEOMETRY_UNIFORM_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_INTEGER_SAMPLES);
	GLIF_CONSTANTI_PRINT(GL_MIN_MAP_BUFFER_ALIGNMENT);
	GLIF_CONSTANTI_PRINT(GL_MAX_LABEL_LENGTH);
	GLIF_CONSTANTI_PRINT(GL_MIN_PROGRAM_TEXEL_OFFSET);
	GLIF_CONSTANTI_PRINT(GL_MAX_RECTANGLE_TEXTURE_SIZE);
	GLIF_CONSTANTI_PRINT(GL_MAX_RENDERBUFFER_SIZE);
	GLIF_CONSTANTI_PRINT(GL_MAX_SAMPLE_MASK_WORDS);
	GLIF_CONSTANTI64_PRINT(GL_MAX_SERVER_WAIT_TIMEOUT);

	/*	*/
	GLIF_CONSTANTI_PRINT(GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS);
	GLIF_CONSTANTI_PRINT(GL_MAX_TESS_CONTROL_ATOMIC_COUNTERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_TESS_EVALUATION_ATOMIC_COUNTERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_TEXTURE_BUFFER_SIZE);
	GLIF_CONSTANTI_PRINT(GL_MAX_TEXTURE_IMAGE_UNITS);
	GLIF_CONSTANTI_PRINT(GL_MAX_TEXTURE_LOD_BIAS);
	GLIF_CONSTANTI_PRINT(GL_MAX_TEXTURE_SIZE);
	GLIF_CONSTANTI_PRINT(GL_MAX_UNIFORM_BUFFER_BINDINGS);
	GLIF_CONSTANTI_PRINT(GL_MAX_UNIFORM_BLOCK_SIZE);
	GLIF_CONSTANTI_PRINT(GL_MAX_UNIFORM_LOCATIONS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VARYING_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VARYING_VECTORS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VARYING_FLOATS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_ATOMIC_COUNTERS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_ATTRIBS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_UNIFORM_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_UNIFORM_VECTORS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_OUTPUT_COMPONENTS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_UNIFORM_BLOCKS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VIEWPORT_DIMS);
	GLIF_CONSTANTI_PRINT(GL_MAX_VIEWPORTS);

	/*	*/
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET);
	GLIF_CONSTANTI_PRINT(GL_MAX_VERTEX_ATTRIB_BINDINGS);
	GLIF_CONSTANTI_PRINT(GL_MAX_ELEMENT_INDEX);

	giDeleteGLContext();

	return EXIT_SUCCESS;
}
